name = "portfolio-daniel-sinambela"
compatibility_date = "2024-01-01"
account_id = "7c8480806f9e5a82872ddf158fa9669a"

# Local development database
[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "4eda5df4-a00a-49c9-9579-518b18a9b4c8"
migrations_dir = "drizzle"

# Production environment
[env.production]
name = "portfolio-daniel-sinambela"

[[env.production.d1_databases]]
binding = "DB"
database_name = "portfolio-db-production"
database_id = "fa5e590c-1acd-4bc8-81c2-80b920220173"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2"
bucket_name = "portfolio-assets"
